### ISSUE TITLE
Get an updated-config

### ISSUE THREAD

**Issue by lucasmichot** [Soullivaneuh/php-cs-fixer-styleci-bridge#57] opened 2016-04-16 14:02 UTC
Any possibility to get an up-to-date config ?
cc/ @GrahamCampbell

**Comment by lucasmichot** [comment] 2016-04-16 14:06
Or maybe https://github.com/StyleCI/SDK

**Comment by GrahamCampbell** [comment] 2016-04-16 15:22
@lucasmichot Duplicate of https://github.com/Soullivaneuh/styleci-fixers/issues/1. ;)

**Comment by Soullivaneuh** [comment] 2016-04-17 10:12
Hi @lucasmichot,

WIP on https://github.com/Soullivaneuh/styleci-fixers/pull/2.

Will update the bridge right after that! :wink:

**Closed** 2016-04-17 12:22 UTC
Labels: minor

**Comment by Soullivaneuh** [comment] 2016-04-17 13:55
Here you go: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/releases/tag/v1.6.0
